name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PSS: ${{ secrets.DOCKER_PSS }}
      run: |
        echo "Iniciando sesión en Docker..."
        echo "$DOCKER_PSS" | docker login -u "$DOCKER_USER" --password-stdin
        echo "Sesión iniciada correctamente."
