name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and get tag
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "major"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}"

      - name: Display Version
        run: |
          echo "New version: ${{ steps.version.outputs.version }}"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PSS }}

      - name: Build Docker Image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t e255997960/docker-graphql:${VERSION} -t e255997960/docker-graphql:latest .

      - name: Push Docker Image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push e255997960/docker-graphql:${VERSION}
          docker push e255997960/docker-graphql:latest
